version: '2.32.0'

services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bank
      - MONGO_INITDB_ROOT_PASSWORD=iWhHEoknqyzfXMAT
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=kUV(F@73eugdw
      - MYSQL_USER=sql
      - MYSQL_PASSWORD=kUV(F@73eugdw
      - MYSQL_DATABASE=scheme
    ports:
      - '3307:3306'

  ecom:
    image: 'ecom:latest'
    ports: 
      - '4000:4000'
    links:
      - redis
      - mongodb
      - mysql
    depends_on:
      - redis
      - mongodb
      - mysql
    environment:
      - MONGO_URI=mongodb://Bank:iWhHEoknqyzfXMAT@mongodb:27017/mydb