version: '3.1'

services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bank
      - MONGO_INITDB_ROOT_PASSWORD=iWhHEoknqyzfXMAT
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - '27017:27017'

  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=scheme'
      - 'MYSQL_PASSWORD=kUV(F@73eugdw'
      - 'MYSQL_ROOT_PASSWORD=kUV(F@73eugdw'
    ports:
      - '3307:3306'

  ecom:
    image: 'ecom:latest'
    ports: 
      - '4000:4000'
    links:
      - redis
      - mongodb
      - mysql
    depends_on:
      - redis
      - mongodb
      - mysql