version: '2.32.0'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    expose:
      - "6379"
    ports: 
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    command: mongod --port 27018
    volumes:      
      - dbdata6:/data/db
    expose:
      - "27018"
      - "27017"
    ports:
      - '27018:27018'
      - '27017:27017'

  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=kUV(F@73eugdw
      - MYSQL_USER=sql
      - MYSQL_PASSWORD=kUV(F@73eugdw
      - MYSQL_DATABASE=scheme
    expose:
      - "3307"
    ports:
      - '3307:3306'

  ecom:
    build: .
    ports: 
      - '4000:4000'
    links:
      - redis
      - mongodb
      - mysql
    depends_on:
      - redis
      - mongodb
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=6379

volumes:  
  dbdata6: